require:
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false
Style/EndOfLine:
  Enabled: false
Documentation:
  Enabled: false
RSpec/MessageSpies:
  Enabled: false
Metrics/BlockLength:
  Max: 50

AllCops:
  Exclude:
    - 'config/application.rb'
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'